config/routes.rb
Mp::Application.routes.draw do
  resources :agents do
    member do
      post :bind_account,:freeze_agent,:restore_agent
    end
    
    collection do
      get :list
    end
  end

  resources :merchant_categories do
    collection do
      get :select
    end
  end

  resources :orders

  resources :accounts do 
    collection do
      get :available_sms_count
    end
    
    member do
      post :change_password
    end
  end
  
  resources :cities
  resources :packages do
    member do 
      get :cal_total_price,:promo_price
    end
    collection do
      get :basic_for_select,:basic,:added,:promos
    end
  end
  
  namespace :plan do
    concern :plan_manage do
      collection do
        get   :options
        post  :filter_user
        get   :filter_user
        post  :preview
      end
      
      member do
        get   :mobiles
      end
    end

    resources :personals,concerns: :plan_manage
    resources :customs  ,concerns: :plan_manage
    resources :unions   ,concerns: :plan_manage
    resources :plans    ,concerns: :plan_manage
    resources :returns  ,concerns: :plan_manage
    resources :news     ,concerns: :plan_manage
    resources :merchants,concerns: :plan_manage
    resources :models   ,concerns: :plan_manage
  end

  resources :name_lists do
    collection do
      get :mobiles
    end
  end
  post '/merchants/:id/update',to: 'merchants#update'
  resources :merchants do
    member do
      post :bind_account,:bind_package,:freeze_merchant,:restore_merchant,:update
      get  :detail,:download_mid_file
    end
    collection do
      get :list,:info_for_buy,:info_for_usage,:info_for_package,:info,:available_sms_count
    end 
  end
  devise_for :members, class_name: "Mp::Member"#,:controllers => {:sessions => "sessions"}
  
  resources :marketings do
    collection do
      get :summary, :follows, :convs, :weidian_detail, :weidian_follow, :weidian_conv
    end
    member do
      get :detail, :follow, :conv
    end
  end

  resources :operates do
    collection do
      get :overview, :dealrecord, :feature, :dealflow, :check, :latestoverview
    end
  end

  resources :report do
    collection do
      get :detail, :summary
    end
  end

  namespace :mp do
    get "consume"
    get "app_visit"
    get "plan_list"
    get "report_list"
    get "report"
    post "save_plan"
    post "preview_plan"
  end

  namespace :sp_result do
    get "summary"
    get "chart"
  end

  resources :sp_reports, :only => [:index] do
    member do
      get :detail, :summary, :program
    end
  end

  root :to => 'welcome#index'

  namespace :api do
    post "store2merchant/notify"
    get "store2merchant/weidian"
  end
end

app/controllers/welcome_controller.rb
#encoding: utf-8

class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
#top_nav
	%a.brand(href="/")
		/ %span.text
		/ 	演示版
	#account_cpanel.clearfix
		.nav-item.member.pull-left
			欢迎你,
			= current_member.user_label
		.nav-item.logout.pull-right
			%a(href = "/members/sign_out" data-method="delete" rel="nofollow")
				退出系统
	#top_bar
#container
	#side_nav
		#logo.hide

		%ul.side-list.top-list.hide
			%li.nav-head
				.icon.icon-1
				账户余额10000元
			%li.nav-head.last
				.icon.icon-2
				信息管理
		%ul.side-list
			%li.nav-head
				.icon.icon-1
				= link_to "首页", "#homepage"
			- if current_member.agent?
				%li.nav-head
					.icon.icon-2
					= link_to "商户管理", "#mch_manage_list"
				%li
					.icon.icon-4
					= link_to "新建商户", "#new_mch_account"
			- else
				%li.nav-head
					.icon.icon-2
					= link_to "短信营销", "#manage_list"
				- if current_member.upsmart?
					%li
						.icon.icon-4
						= link_to "老客户推送", "#admin_push_1"
					%li
						.icon.icon-4
						= link_to "潜在客户推送", "#admin_push_2"
					%li
						.icon.icon-4
						= link_to "个性化筛选推送", "#property_push"
					%li
						.icon.icon-4
						= link_to "自定义名单推送", "#admin_push_4"
					%li
						.icon.icon-4
						= link_to "指定商户触发推送", "#admin_push_5"
					%li
						.icon.icon-4
						= link_to "模型触发推送", "#admin_push_6"
					%li.nav-head
						.icon.icon-2
						= link_to "商户管理", "#mch_manage_list"
					%li
						.icon.icon-4
						= link_to "新建商户", "#new_mch_account"
					%li.nav-head
						.icon.icon-2
						= link_to "代理账户管理", "#agent_manage_list"
					%li
						.icon.icon-4
						= link_to "新建代理账户", "#new_agent_account"
				- else
					%li
						.icon.icon-4
						= link_to "个性化筛选推送", "#property_push"
					%li
						.icon.icon-4
						= link_to "自定义名单推送", "#custom_push"
				- unless current_member.upsmart?
					%li.nav-head
						.icon.icon-5
						= link_to "银联微点", "#new_app"
					%li
						.icon.icon-4
						= link_to "效果统计", "#app_push"
					%li.nav-head
						.icon.icon-3
						= link_to "月度经营分析报告", "#month_analytics"
					%li.nav-head
						.icon.icon-3
						= link_to "套餐使用情况查询", "#package_info"

	#article
	.copyright.hide
		沪ICP备13002437号-1    Copyright &copy; 2013 银联智惠
- content_for :footer do
	- if current_member.upsmart?
		#init(data-js="SmartMerchantAdmin")
	- elsif current_member.agent?
		#init(data-js="SmartMerchantAgent")
	- else
		#init(data-js="SmartMerchant")